[project]
name = "Shawarma"
version = "0.0.1"
dependencies = [
    "openai",
    "torch",
    "torchvision",
    "torchaudio",
    "scapy",
    "scikit-learn",
    "matplotlib",
    "pandas",
    "numpy",
    "torchlens",
    "grpcio",
    "protobuf",
]
